name: Triggers

on:
    schedule:
      - cron: '01 22 * * *'  

    workflow_dispatch:
      inputs:
        lenguaje_favorito:
          description: 'Lenguaje favorito'
          default: Java
          required: true
          type: choice
          options:
          - Java
          - Python
          - Go

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Definir lenguaje
        run: echo "LANGUAGE=${{ inputs.lenguaje_favorito }}" >> $GITHUB_ENV

      - name: Compile Main.java
        run: javac src/Main.java

      - name: Run Main
        run: java -cp src Main
        
